(function(){
  window.const = window.const || {};

  window.const.lang = {
    list:  {
      'Auto': 'auto',
      'Afrikaans': 'af',
      'Albanian': 'sq',
      'Arabic': 'ar',
      'Armenian': 'hy',
      'Azerbaijani': 'az',
      'Basque': 'eu',
      'Belarusian': 'be',
      'Bengali': 'bn',
      'Bosnian': 'bs',
      'Bulgarian': 'bg',
      'Catalan': 'ca',
      'Cebuano': 'ceb',
      'Chichewa': 'ny',
      'ChineseSimplified': 'zh-CN',
      'ChineseTraditional': 'zh-TW',
      'Croatian': 'hr',
      'Czech': 'cs',
      'Danish': 'da',
      'Dutch': 'nl',
      'English': 'en',
      'EnglishUS': 'en-US',
      'Esperanto': 'eo',
      'Estonian': 'et',
      'Filipino': 'tl',
      'Finnish': 'fi',
      'French': 'fr',
      'Galician': 'gl',
      'Georgian': 'ka',
      'German': 'de',
      'Greek': 'el',
      'Gujarati': 'gu',
      'HaitianCreole': 'ht',
      'Hausa': 'ha',
      'Hebrew': 'iw',
      'Hindi': 'hi',
      'Hmong': 'hmn',
      'Hungarian': 'hu',
      'Icelandic': 'is',
      'Igbo': 'ig',
      'Indonesian': 'id',
      'Irish': 'ga',
      'Italian': 'it',
      'Javanese': 'jw',
      'Japanese': 'ja',
      'Kannada': 'kn',
      'Kazakh': 'kk',
      'Khmer': 'km',
      'Korean': 'ko',
      'Lao': 'lo',
      'Latin': 'la',
      'Latvian': 'lv',
      'Lithuanian': 'lt',
      'Macedonian': 'mk',
      'Malagasy': 'mg',
      'Malay': 'ms',
      'Maltese': 'mt',
      'Maori': 'mi',
      'Marathi': 'mr',
      'Mongolian': 'mn',
      'Nepali': 'ne',
      'Norwegian': 'no',
      'Persian': 'fa',
      'Polish': 'pl',
      'Portuguese': 'pt',
      'Punjabi': 'pa',
      'Romanian': 'ro',
      'Russian': 'ru',
      'Serbian': 'sr',
      'Sesotho': 'st',
      'Sinhala': 'si',
      'Slovak': 'sk',
      'Slovenian': 'sl',
      'Somali': 'so',
      'Spanish': 'es',
      'Sundanese': 'su',
      'Swahili': 'sw',
      'Swedish': 'sv',
      'Tajik': 'tg',
      'Tamil': 'ta',
      'Telugu': 'te',
      'Thai': 'th',
      'Turkish': 'tr',
      'Ukrainian': 'uk',
      'Urdu': 'ur',
      'Uzbek': 'uz',
      'Vietnamese': 'vi',
      'Welsh': 'cy',
      'Yiddish': 'yi',
      'Yoruba': 'yo',
      'Zulu': 'zu',
      'Malayalam': 'ml',
      'MyanmarBurmese': 'my',

      'Amharic': 'am',
      'Corsican': 'co',
      'Frisian': 'fy',
      'Hawaiian': 'haw',
      'KurdishKurmanji': 'ku',
      'Kyrgyz': 'ky',
      'Luxembourgish': 'lb',
      'Pashto': 'ps',
      'Samoan': 'sm',
      'ScotsGaelic': 'gd',
      'Shona': 'sn',
      'Sindhi': 'sd',
      'Xhosa': 'xh'
    },
    reversed: {
      'auto':'Auto',
      'af':'Afrikaans',
      'sq':'Albanian',
      'ar':'Arabic',
      'hy':'Armenian',
      'az':'Azerbaijani',
      'eu':'Basque',
      'be':'Belarusian',
      'bn':'Bengali',
      'bs':'Bosnian',
      'bg':'Bulgarian',
      'ca':'Catalan',
      'ceb':'Cebuano',
      'ny':'Chichewa',
      'zh-CN':'ChineseSimplified',
      'zh-TW':'ChineseTraditional',
      'hr':'Croatian',
      'cs':'Czech',
      'da':'Danish',
      'nl':'Dutch',
      'en':'English',
      'en-US':'EnglishUS',
      'eo':'Esperanto',
      'et':'Estonian',
      'tl':'Filipino',
      'fi':'Finnish',
      'fr':'French',
      'gl':'Galician',
      'ka':'Georgian',
      'de':'German',
      'el':'Greek',
      'gu':'Gujarati',
      'ht':'HaitianCreole',
      'ha':'Hausa',
      'iw':'Hebrew',
      'hi':'Hindi',
      'hmn':'Hmong',
      'hu':'Hungarian',
      'is':'Icelandic',
      'ig':'Igbo',
      'id':'Indonesian',
      'ga':'Irish',
      'it':'Italian',
      'jw':'Javanese',
      'ja':'Japanese',
      'kn':'Kannada',
      'kk':'Kazakh',
      'km':'Khmer',
      'ko':'Korean',
      'lo':'Lao',
      'la':'Latin',
      'lv':'Latvian',
      'lt':'Lithuanian',
      'mk':'Macedonian',
      'mg':'Malagasy',
      'ms':'Malay',
      'mt':'Maltese',
      'mi':'Maori',
      'mr':'Marathi',
      'mn':'Mongolian',
      'ne':'Nepali',
      'no':'Norwegian',
      'fa':'Persian',
      'pl':'Polish',
      'pt':'Portuguese',
      'pa':'Punjabi',
      'ro':'Romanian',
      'ru':'Russian',
      'sr':'Serbian',
      'st':'Sesotho',
      'si':'Sinhala',
      'sk':'Slovak',
      'sl':'Slovenian',
      'so':'Somali',
      'es':'Spanish',
      'su':'Sundanese',
      'sw':'Swahili',
      'sv':'Swedish',
      'tg':'Tajik',
      'ta':'Tamil',
      'te':'Telugu',
      'th':'Thai',
      'tr':'Turkish',
      'uk':'Ukrainian',
      'ur':'Urdu',
      'uz':'Uzbek',
      'vi':'Vietnamese',
      'cy':'Welsh',
      'yi':'Yiddish',
      'yo':'Yoruba',
      'zu':'Zulu',
      'ml':'Malayalam',
      'my':'MyanmarBurmese',
      'am':'Amharic',
      'co':'Corsican',
      'fy':'Frisian',
      'haw':'Hawaiian',
      'ku':'KurdishKurmanji',
      'ky':'Kyrgyz',
      'lb':'Luxembourgish',
      'ps':'Pashto',
      'sm':'Samoan',
      'gd':'ScotsGaelic',
      'sn':'Shona',
      'sd':'Sindhi',
      'xh':'Xhosa'
    }
  };
})();
